{"Kategory":[
{"cat_id":9999,
"kategory":"Telegram Grubumuz",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Telegram Grubumuz",
"cat_url":"https://t.me/joinchat/MNLF0w-V4XwQZJOSr6kzMw",
"cat_foto":"https://1.bp.blogspot.com/-7vi-miz6tSc/XWseU6ipwbI/AAAAAAAAATc/qqvWZ8xswQ0YzCW4VCC4cBarOgE4aSIhwCLcBGAs/s1600/PicsArt_09-01-03.20.32.png"},

{"cat_id":9998,
"kategory":"Müzik Player",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Müzik Player",
"cat_url":"http://www.globalcanlitv.rf.gd/muzik-player.html?i=1",
"cat_foto":"https://1.bp.blogspot.com/-9YXbWQVscu0/XreH4DlczWI/AAAAAAAABb4/hTkWhmy55dsX9NpN51CA6v59pLmLesTKQCK4BGAsYHg/s250/PicsArt_05-01-03.50.29.jpg"},

{"cat_id":9997,
"kategory":"Bugün Tv'de Ne Var?",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"",
"cat_url":"",
"cat_foto":"https://2.bp.blogspot.com/-1hz606Vmpyo/Xnq5GlZ8mKI/AAAAAAAABDw/Z5W4nX_AX8cqdVIilib1BYl5DF6uhqR_wCLcBGAsYHQ/s1600/PicsArt_03-25-02.50.27.png"},
{"cat_id":9996,
"kategory":"Program Rehberi",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Program Rehberi",
"cat_url":"",
"cat_foto":"https://1.bp.blogspot.com/-GfYtOZLK1R8/X6RnijEHnVI/AAAAAAAABsY/DocIXjL9piUKZ8CxyddoVPKO64dZAzxRQCLcBGAsYHQ/s0/PicsArt_11-05-09.57.51.png"},

{"cat_id":9998,
"kategory":"Spor, Belgesel, Sinema Kanalları Hakkında!",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Spor, Belgesel, Sinema Kanalları Hakkında!",
"cat_url":"https://iptvpro93.github.io/bilgikanal.html",
"cat_foto":"https://1.bp.blogspot.com/-7YsGGz8qTc4/X8wRPM2aRgI/AAAAAAAAAxY/fKm_FqwJQccPtZxozWmB_YD3Mtc3ufs8ACLcBGAsYHQ/s0/PicsArt_12-05-11.58.55.png"},

{"cat_id":888,
"kategory":"Ulusal",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey\/Ulusal",
"cat_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/turkey/ulusal.txt",
"cat_foto":"http://www.freelogovectors.net/wp-content/uploads/2013/02/TV-Icon-9.png"},

{"cat_id":888,
"kategory":"Spor",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey\/Spor",
"cat_url":"https://dl.dropboxusercontent.com/s/7b5ft0sin5i783g/spor.txt?dl=0",
"cat_foto":"http://www.freelogovectors.net/wp-content/uploads/2013/02/TV-Icon-9.png"},

{"cat_id":888,
"kategory":"Belgesel",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey\/Belgesel",
"cat_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/turkey/belgesel.txt",
"cat_foto":"http://www.freelogovectors.net/wp-content/uploads/2013/02/TV-Icon-9.png"},

{"cat_id":888,
"kategory":"Haber",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey\/Haber",
"cat_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/turkey/haber.txt",
"cat_foto":"http://www.freelogovectors.net/wp-content/uploads/2013/02/TV-Icon-9.png"},

{"cat_id":888,
"kategory":"Müzik",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey\/Müzik",
"cat_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/turkey/muzik.txt",
"cat_foto":"http://www.freelogovectors.net/wp-content/uploads/2013/02/TV-Icon-9.png"},

{"cat_id":888,
"kategory":"Çocuk",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey\/Çocuk",
"cat_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/turkey/cocuk.txt",
"cat_foto":"http://www.freelogovectors.net/wp-content/uploads/2013/02/TV-Icon-9.png"},

{"cat_id":888,
"kategory":"Dini",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey\/Dini",
"cat_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/turkey/dini.txt",
"cat_foto":"http://www.freelogovectors.net/wp-content/uploads/2013/02/TV-Icon-9.png"},

{"cat_id":888,
"kategory":"Sinema",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey\/Sinema",
"cat_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/turkey/sinema.txt",
"cat_foto":"http://www.freelogovectors.net/wp-content/uploads/2013/02/TV-Icon-9.png"},

{"cat_id":888,
"kategory":"Yerel",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey\/Yerel",
"cat_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/turkey/yerel.txt",
"cat_foto":"http://www.freelogovectors.net/wp-content/uploads/2013/02/TV-Icon-9.png"},
]}
