{"Ulke":[
{"ulke_id":9999,
"country":"🛡Eski v4.8.4 Ücretli Full Özellikli Yükle(1 Gün ⬇️%30 İndirim)",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"🛡Eski v4.8.4 Ücretli Full Özellikli Yükle(5 Gün ⬇️%30 İndirim)",
"ulke_url":"https://play.google.com/store/apps/details?id=com.canliglobaltvpro.android",
"country_foto":"https://1.bp.blogspot.com/-qSqhbbYFzbM/X7_VDL4t1eI/AAAAAAAABtQ/55FxOHeaUEAVejIGRqHH9RmargAXeiKmgCLcBGAsYHQ/s0/PicsArt_11-26-05.14.01.png"},

{"ulke_id":6,
"country":"Turkey",
"ulke_flag":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png",
"ulke":"Turkey",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/turkey/turkey.php",
"country_foto":"https://1.bp.blogspot.com/-I4ms6mqyBI4/X5GHSfPOHpI/AAAAAAAABrM/DMSNOXs15FU8eLg2sKuGECBsSDmfqHgpgCLcBGAsYHQ/s0/turkey.png"},

{"ulke_id":12,
"country":"Germany",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/germany.png",
"ulke":"Germany",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/germany/germany.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/germany.png"},

{"ulke_id":7,
"country":"Azerbaijan",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/azeri.png",
"ulke":"Azerbaijan",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/azerbaijan/azerbaijan.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/azeri.png"},

{"ulke_id":34,
"country":"Kurdish",
"ulke_flag":"https://1.bp.blogspot.com/-yuIcE3kYeOA/X6SL2N_v4bI/AAAAAAAABsk/GGBXystwMjcK_q2sKtWbYX4ySmim11AagCLcBGAsYHQ/s0/flag_kurdistan.png",
"ulke":"Kurdish",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/kurdish/kurdish.php",
"country_foto":"https://1.bp.blogspot.com/-yuIcE3kYeOA/X6SL2N_v4bI/AAAAAAAABsk/GGBXystwMjcK_q2sKtWbYX4ySmim11AagCLcBGAsYHQ/s0/flag_kurdistan.png"},

{"ulke_id":1,
"country":"Bulgaria",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/bulgaria.png",
"ulke":"Bulgaria",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/bulgaria/bulgaria.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/bulgaria.png"},

{"ulke_id":2,
"country":"Poland",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/poland.png",
"ulke":"Poland",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/poland/poland.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/poland.png"},

{"ulke_id":8,
"country":"Spain",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/spain.png",
"ulke":"Spain",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/spain/spain.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/spain.png"},

{"ulke_id":4,
"country":"Albania",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/albania.png",
"ulke":"Albania",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/albania/albania.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/albania.png"},

{"ulke_id":5,
"country":"Czechia",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/czechia.png",
"ulke":"Czechia",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/czechia/czechia.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/czechia.png"},

{"ulke_id":8,
"country":"North Cyprus",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/kibris.png",
"ulke":"North Cyprus",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/north-cyprus/north-cyprus.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/kibris.png"},

{"ulke_id":10,
"country":"Ukraine",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/Ukraine.png",
"ulke":"Ukraine",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/ukraine/ukraine.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/Ukraine.png"},

{"ulke_id":11,
"country":"Belarus",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/belarus.png",
"ulke":"Belarus",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/belarus/belarus.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/belarus.png"},

{"ulke_id":9,
"country":"Russia",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/russia.png",
"ulke":"Russia",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/russia/russia.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/russia.png"},

{"ulke_id":13,
"country":"America",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/usa.png",
"ulke":"America",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/america/america.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/usa.png"},

{"ulke_id":14,
"country":"Argentina",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/argentina.png",
"ulke":"Argentina",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/argentina/argentina.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/argentina.png"},

{"ulke_id":15,
"country":"Armenia",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/armenia.png",
"ulke":"Armenia",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/armenia/armenia.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/armenia.png"},

{"ulke_id":32,
"country":"Belgium",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/belgium.png",
"ulke":"Belgium",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/belgium/belgium.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/belgium.png"},

{"ulke_id":16,
"country":"Brazil",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/brasil.png",
"ulke":"Brazil",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/brasil/brasil.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/brasil.png"},

{"ulke_id":17,
"country":"Egypt",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/egypt.png",
"ulke":"Egypt",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/egypt/egypt.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/egypt.png"},

{"ulke_id":18,
"country":"France",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/france.png",
"ulke":"France",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/france/france.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/france.png"},

{"ulke_id":19,
"country":"Georgia",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/georgia.png",
"ulke":"Georgia",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/georgia/georgia.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/georgia.png"},

{"ulke_id":20,
"country":"Greece",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/greece.png",
"ulke":"Greece",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/greece/greece.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/greece.png"},

{"ulke_id":21,
"country":"Hungary",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/hungary.png",
"ulke":"Hungary",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/hungary/hungary.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/hungary.png"},

{"ulke_id":22,
"country":"Indonesia",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/indonesia.png",
"ulke":"Indonesia",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/indonesia/indonesia.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/indonesia.png"},

{"ulke_id":23,
"country":"Israel",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/israel.png",
"ulke":"Israel",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/israel/israel.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/israel.png"},

{"ulke_id":24,
"country":"Italy",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/italy.png",
"ulke":"Italy",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/italy/italy.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/italy.png"},

{"ulke_id":25,
"country":"Kazakhstan",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/Kazakhstan.png",
"ulke":"Kazakhstan",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/kazakhstan/kazakhstan.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/Kazakhstan.png"},

{"ulke_id":26,
"country":"Mexico",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/mexico.png",
"ulke":"Mexico",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/mexico/mexico.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/mexico.png"},

{"ulke_id":27,
"country":"Moldova",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/moldova.png",
"ulke":"Moldova",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/moldova/moldova.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/moldova.png"},

{"ulke_id":28,
"country":"Morocco",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/morocco.png",
"ulke":"Morocco",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/morocco/morocco.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/morocco.png"},

{"ulke_id":33,
"country":"Netherlands",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/netherlands.png",
"ulke":"Netherlands",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/netherlands/netherlands.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/netherlands.png"},

{"ulke_id":29,
"country":"Romania",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/romanya.png",
"ulke":"Romania",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/romania/romania.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/romanya.png"},

{"ulke_id":30,
"country":"Slovakia",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/slovakia.png",
"ulke":"Slovakia",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/slovakia/slovakia.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/slovakia.png"},

{"ulke_id":31,
"country":"United Kingdom",
"ulke_flag":"http://213.128.89.165/Main/Flag/owl_bayrak/uk.png",
"ulke":"United Kingdom",
"ulke_url":"https://github.com/herix0/herix0.github.io/raw/master/app/ch/united-kingdom/united-kingdom.php",
"country_foto":"http://213.128.89.165/Main/Flag/owl_bayrak/uk.png"},

]}
